updated, removed unnecessary variables and checks

diff --git a/webmon b/webmon
--- a/webmon
+++ b/webmon
@@ -1,23 +1,29 @@
 #!/bin/bash
 
-WM_DIR="/tmp/webmon";
-FULL_URL="http://ocf.mbentley.net/forums/";
-SHORT_URL="ocf.mbentley.net";
+WM_DIR="/tmp/webmon"
+SHORT_URL=${1}
+FULL_URL=${2}
 
-#log_file="/var/www/athena.casa.mbentley.net/webmon_logs/webmon.${SHORT_URL}.txt";
-DOWN_FILE="down.${SHORT_URL}";
-#COMMAND=$0
-EMAIL=$1
+DOWN_FILE="down.${SHORT_URL}"
+EMAIL_TO=mbentley@arcus.io
+EMAIL_FROM=noreply@roche.com
 OFFLINE_COUNT=0
-#OFFLINE_COUNT_OTHER=0
+SENDMAIL=/usr/bin/mail
 
-function email_check {
-	if [ -z ${EMAIL} ]
+function check_vars {
+	if [ -z ${SHORT_URL} ]
 	then
-		EMAIL=mbentley@mbentley.net
+		echo -e "You must provide a short URL name as the first parameter\nExample:  ${0} google.com http://www.google.com/"
+		exit 1
 	fi
 
-	temp_dir
+	if [ -z ${LONG_URL} ]
+	then
+		echo -e "You must provide a long URL as the second parameter\nExample:  ${0} google.com http://www.google.com/"
+		exit 1
+	else
+		temp_dir
+	fi
 }
 
 function temp_dir {
@@ -26,44 +32,25 @@ function temp_dir {
 		mkdir ${WM_DIR}
 	fi
 
-	if [ ! -f ${log_file} ]
+	TEMPDIR=/tmp/webmon_${SHORT_URL}_`date +%N`
+	mkdir ${TEMPDIR}
+	if [ ! -d "${TEMPDIR}" ]
 	then
-		echo -e "STATUS\tDATE/TIME\t\tSTATUS CODE" >> ${log_file}
-	fi
-
-	tempdir=/tmp/webmon_${SHORT_URL}_`date +%N`
-	mkdir ${tempdir}
-	if [ ! -d "${tempdir}" ]
-	then
-		echo "unable to create temp directory";
+		echo "unable to create temp directory"
 		exit 1
 	fi
-	internet_check
-}
-
-function internet_check {
-	inet_check=`curl -m 15 -s -I -q http://www.google.com | grep HTTP | awk '{ print $2 }'`
-
-	if [ ${inet_check} != "200" ]
-	then
-		echo "internet connection test failed"
-		echo "skipping webmon check for ${SHORT_URL}"
-		cleanup_tmp
-	else
-		echo "internet connection test successful"
-		query_status
-	fi
+	query_status
 }
 
 function query_status {
-	full_status_code=`curl -m 15 -s -I -q ${FULL_URL} | grep HTTP`
-	short_status_code=`echo ${full_status_code} | awk '{ print $2 }'`
+	FULL_STATUS_CODE=`curl -m 15 -s -I -q ${FULL_URL} | grep HTTP`
+	SHORT_STATUS_CODE=`echo ${FULL_STATUS_CODE} | awk '{ print $2 }'`
 
-	if [ $short_status_code != "200" ]
+	if [ ${SHORT_STATUS_CODE} != "200" ]
 	then
 		verify_offline
 	else
-		echo "${full_status_code}";
+		echo "${FULL_STATUS_CODE}"
 		online_check
 	fi
 }
@@ -73,7 +60,7 @@ function verify_offline {
 
 	if [ ${OFFLINE_COUNT} == 3 ]
 	then
-		echo "${full_status_code}";
+		echo "${FULL_STATUS_CODE}"
 		email_offline
 	else
 		sleep 1
@@ -84,22 +71,18 @@ function verify_offline {
 function online_check {
 	if [ -f ${WM_DIR}/${DOWN_FILE} ]
 	then
-		# log the end of the outage
-		echo -e "UP\t`date +%F" "%R" "%Z`\t${full_status_code}" >> ${log_file}
-
 		rm ${WM_DIR}/${DOWN_FILE}
-		mail=${tempdir}/mail_`date +%F`
-		touch $mail
-		chmod 600 $mail
-		echo "To: ${EMAIL}" >> $mail
-		echo "From: ${EMAIL}" >> $mail
-		echo "Subject: webmon: ${SHORT_URL} is back online" >> $mail
-		echo "" >> $mail
-		echo "webmon status:" >> $mail
-		echo "     ${FULL_URL} is back online" >> $mail
-		echo "     ${full_status_code}" >> $mail
-		echo -e "\nwebmon logs: http://`hostname -f`/webmon_logs/webmon.${SHORT_URL}.txt" >> $mail
-		/usr/sbin/sendmail -t -f mbentley@mbentley.net < $mail
+		MAIL=${TEMPDIR}/mail_`date +%F`
+		touch ${MAIL}
+		chmod 600 ${MAIL}
+		echo "To: ${EMAIL_TO}" >> ${MAIL}
+		echo "From: ${EMAIL_FROM}" >> ${MAIL}
+		echo "Subject: webmon: ${SHORT_URL} is back online" >> ${MAIL}
+		echo "" >> ${MAIL}
+		echo "webmon status:" >> ${MAIL}
+		echo "     ${FULL_URL} is back online" >> ${MAIL}
+		echo "     ${FULL_STATUS_CODE}" >> ${MAIL}
+		${SENDMAIL} -t -f ${EMAIL_TO} < ${MAIL}
 	fi
 
 	cleanup_tmp
@@ -108,21 +91,17 @@ function online_check {
 function email_offline {
 	if [ ! -f ${WM_DIR}/${DOWN_FILE} ]
 	then
-		# log the start of the outage
-		echo -e "DOWN\t`date +%F" "%R" "%Z`\t${full_status_code}" >> ${log_file}
-
-		mail=${tempdir}/mail_`date +%F`
-		touch $mail
-		chmod 600 $mail
-		echo "To: ${EMAIL}" >> $mail
-		echo "From: ${EMAIL}" >> $mail
-		echo "Subject: webmon: ${SHORT_URL} is offline" >> $mail
-		echo "" >> $mail
-		echo "webmon status:" >> $mail
-		echo "     ${FULL_URL} is currently offline" >> $mail
-		echo "     ${full_status_code}" >> $mail
-		echo -e "\nwebmon logs: http://`hostname -f`/webmon_logs/webmon.${SHORT_URL}.txt" >> $mail
-		/usr/sbin/sendmail -t -f mbentley@mbentley.net < $mail
+		MAIL=${TEMPDIR}/mail_`date +%F`
+		touch ${MAIL}
+		chmod 600 ${MAIL}
+		echo "To: ${EMAIL_TO}" >> ${MAIL}
+		echo "From: ${EMAIL_FROM}" >> ${MAIL}
+		echo "Subject: webmon: ${SHORT_URL} is offline" >> ${MAIL}
+		echo "" >> ${MAIL}
+		echo "webmon status:" >> ${MAIL}
+		echo "     ${FULL_URL} is currently offline" >> ${MAIL}
+		echo "     ${FULL_STATUS_CODE}" >> ${MAIL}
+		${SENDMAIL} -t -f ${EMAIL_TO} < ${MAIL}
 	fi
 
 	touch ${WM_DIR}/${DOWN_FILE}
@@ -131,8 +110,8 @@ function email_offline {
 }
 
 function cleanup_tmp {
-	rm -rf ${tempdir}
+	rm -rf ${TEMPDIR}
 	exit 0
 }
 
-email_check
+check_vars
